import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/provider";
import CentuariNavbar from "@/components/centuari-navbar";
import { switzer } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} relative font-mono antialiased bg-black`}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        <main
          className="mx-auto max-w-full py-2.5 text-foreground min-h-screen"
          style={{
            backgroundImage: 'url("/bg-centuari.png")',
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          <div className="fixed inset-0 -z-10 bg-black" />
          <CentuariNavbar />
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
